# Generated by Django 3.2.5 on 2021-07-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='keywords',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
